[build]
  command = "hugo --theme=hugo-theme-hello-friend --buildDrafts --gc --minify"
  publish = "public"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
